name: test-routine

on: [push]

jobs:
  tests-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: install dependencies of project
        run: npm install
      - name: run test suite
        run: npm test
